### PR TITLE
add direct download info

### PR DESCRIPTION
**Pull request by davwheat**

### CODE REVIEW

**Comment by qgustavor** [comment]
It's not the same thing that is below "How to use"? "When downloading a file replace `https://mega.nz` with `https://directme.ga`". Maybe we can make it easier to users by making [a form](https://directme.ga/splitter) where they enter the original MEGA URL and it returns the Direct MEGA URL...

By the way: you don't need to replace the "#" with a "?" as it's handled for you since [this change](https://github.com/qgustavor/direct-mega/commit/522fb9397437dc49c6ebfa3d5d55ea0be7acb20e#diff-aa50e0dbefe3259b6e91300af13d3479R183).

**Comment by davwheat** [comment]
However, one gives you a direct download, one links you with a direct
download. The direct download link is a necessity for my use.

**Comment by qgustavor** [comment]
As it runs in a browser there's no difference between those: loading with "#" will redirect to "?" automatically. Trying to load it outside a browser will download [this HTML page](https://github.com/qgustavor/direct-mega/blob/master/dist/index.html).

As Foreign Fetch [will be removed](https://github.com/w3c/ServiceWorker/issues/1188) from the spec if you try to load content from Direct MEGA using something like `` the Service Worker will not be called and it will not work (it will load the HTML page).

Is there some situation where the redirect don't works? Also, how changing the readme will improve that?

**Comment by qgustavor** [comment]
Closing as there wasn't a response.

**Pull request closed without merging**
